### ISSUE TITLE
Bug in Half-normal function

### ISSUE THREAD

**Issue by dslramsey** [scrogster/nimbleDistance#7]
I think there is a bug in the dHN.r code where you calculate the analytical integral for line transects.  Currently it is 

`integral=pnorm(Xmax, 0, sigma)-0.5`

However, I think the analytical integral should be

`integral = 2*(pnorm(Xmax, 0, sigma)-0.5) * sqrt(pi/2) * sigma`
 
I think the point transect one is OK

**Comment by scrogster** [comment]
Thanks Dave.

**Comment by scrogster** [comment]
Bug is now corrected in dHN.R

**Comment by scrogster** [comment]
closing bug.
